//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LossTypeData.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dev_LossType
    {
        public int LossTypeID { get; set; }
        public string LossTypeCode { get; set; }
        public string LossTypeDescription { get; set; }
    }
}
